import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import Search from '../components/Search/Search';
import Card from '../components/Card/Card';
import Pagination from '../components/Pagination/Pagination';
import Filter from '../components/Filter/Filter';
import Navbar from '../components/Navbar/Navbar';
import { Box, Heading, Button, Flex } from 'rebass';

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Rick and Morty Wiki</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.jpg' />
      </Head>

      <Navbar />
      <Search />
      <Flex>
        <Filter />
        <Box>
          <Card />
          <Pagination />
        </Box>
      </Flex>
    </Box>
  );
}
