import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import Search from '../components/Search/Search';
import Cards from '../components/Card/Cards';
import PaginationBar from '../components/Pagination/Pagination';
import Filter from '../components/Filter/Filter';
import Navbar from '../components/Navbar/Navbar';
import { Box, Flex } from 'rebass';

let api = `https://rickandmortyapi.com/api/character/?page=1`;

export default function Home(props) {
  let [fetchedData, updateFetchedData] = useState(props.posts);
  let { info, results } = fetchedData;
  return (
    <Box>
      <Head>
        <title>Rick and Morty Wiki</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.jpg' />
      </Head>
      <Navbar />
      <Search />
      <Flex
        mx={['auto']}
        my={['1', '4']}
        flexDirection={['column', 'row']}
        width={['82%']}
        sx={{
          position: 'relative',
        }}
      >
        <Box
          width={['100%', '30%']}
          sx={{
            position: 'absolute',
            left: '0',
          }}
        >
          <Filter />
        </Box>
        <Box
          mt={['6', '1']}
          pb={4}
          width={['100%', '70%']}
          sx={{
            position: 'absolute',
            right: '0',
          }}
        >
          <Cards results={results} />
          <PaginationBar />
        </Box>
      </Flex>
    </Box>
  );
}

export async function getStaticProps() {
  let data = await fetch(api).then((res) => res.json());
  return {
    props: {
      posts: data,
    },
  };
}
