import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import Search from '../components/Search/Search';
import Cards from '../components/Card/Cards';
import PaginationBar from '../components/Pagination/Pagination';
import Filter from '../components/Filter/Filter';
import Navbar from '../components/Navbar/Navbar';
import { Box, Flex } from 'rebass';
import { useRouter } from 'next/router';

let PAGE_API = `https://rickandmortyapi.com/api/character/`;

export default function Home({ posts = [] }) {
  let [pageNumber, updatePageNumber] = useState(1);
  let [fetchedData, updateFetchedData] = useState(posts);
  let [searchTerm, setSearchTerm] = useState('');
  let [status, setStatus] = useState('');
  let [gender, setGender] = useState('');
  let [species, setSpecies] = useState('');
  let { info, results = [] } = fetchedData;

  let api =
    PAGE_API +
    `?page=${pageNumber}&name=${searchTerm}&status=${status}&gender=${gender}&species=${species}`;

  useEffect(() => {
    (async function () {
      let data = await fetch(api).then((res) => res.json());
      updateFetchedData(data);
    })();
  }, [api]);

  return (
    <Box>
      <Head>
        <title>Rick and Morty Wiki</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.jpg' />
      </Head>
      <Navbar />
      <Search setSearchTerm={setSearchTerm} />
      <Flex
        flexDirection={['column', 'row']}
        mx={['auto']}
        mt={['0', '4']}
        width={'85%'}
      >
        <Box width={['100%', '25%']}>
          <Filter />
        </Box>
        <Box mt={['4', '1']} pb={4} width={['100%', '75%']}>
          <Cards results={results} />
          <PaginationBar
            info={info}
            pageNumber={pageNumber}
            updatePageNumber={updatePageNumber}
          />
        </Box>
      </Flex>
    </Box>
  );
}

// export async function getStaticProps() {
//   let data = await fetch(PAGE_API).then((res) => res.json());
//   return {
//     props: {
//       posts: data,
//     },
//   };
// }
