import Navbar from '../../components/Navbar/Navbar';
import Head from 'next/head';

export default function Episodes() {
  return (
    <>
      <Navbar />
      <Head>
        <title>Rick and Morty Wiki</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.jpg' />
      </Head>
    </>
  );
}
